[security]
proxycert="/security/proxy-tls.crt"
proxykey="/security/proxy-tls.pem"
trustedcerts="/security/trusted-tls.crt"

[database]
host="mysql.hub.internal"
port=3306
default="CELLERY_HUB"
user="celleryhub"
password="celleryhub"

[docker.registry]
url="https://docker-registry.hub.internal:5000"

[docker.auth]
issuer="auth.registry.hub.cellery.io"
audience="Docker registry"
certalias="docker.auth"

[b7a.log]
level="DEBUG"
