node_js:
  - 9.11.2
go:
  - 1.11.x
services:
  - docker
cache:
  directories:
    - .autoconf
before_install:
  - npm i -g npm
script:
  - make clean init check-style build test docker
after_success:
  - bash <(curl -s https://codecov.io/bash)
