version: "3"
services:
  hub.cellery.io:
    image: wso2cellery/cellery-hub-portal:latest
    restart: always
    ports:
      - "9000:9000"
    environment:
      - PORTAL_PORT=9000
  registry.hub.cellery.io:
    image: wso2cellery/cellery-hub-proxy:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./proxy/security:/security
      - ./proxy/conf:/conf
    environment:
      - PROXY_CONF=/conf/proxy.toml
  auth.registry.hub.cellery.io:
    image: wso2cellery/cellery-hub-auth:latest
    command: -logtostderr=true /conf/docker-auth.yml
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./docker-auth/conf:/conf
      - ./docker-registry/security:/security
      - ./docker-auth/extension-logs:/extension-logs
    environment:
      - IDP_CERT=/security/idp.crt
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/security/docker-auth-sign.crt
      - REGISTRY_AUTH_TOKEN_ISSUER="auth.registry.hub.cellery.io"
      - IS_JWT=false
      - IDP_HOST=localhost
      - IDP_PORT=9443
      - USERNAME=admin
      - PASSWORD=admin
  docker-registry.hub.internal:
    image: registry:2
    restart: always
    volumes:
      - ./docker-registry/security:/security
      - ./docker-registry/mnt:/mnt
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/mnt
      - REGISTRY_AUTH_TOKEN_REALM=https://auth.registry.hub.cellery.io:5001/auth
      - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
      - REGISTRY_AUTH_TOKEN_ISSUER="auth.registry.hub.cellery.io"
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/security/docker-auth-sign.crt
      - REGISTRY_HTTP_TLS_CERTIFICATE=/security/docker-registry-TLS.crt
      - REGISTRY_HTTP_TLS_KEY=/security/docker-registry-TLS.key
      - REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED=true
      - REGISTRY_HTTP_HOST=https://registry.hub.cellery.io:9090
  mysql.hub.internal:
    image: mysql:8.0.16
    restart: always
    volumes:
      - ./mysql/dbscripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
