swagger: "2.0"
info:
  version: "0.1.0"
  title: "Cellery Hub API"
  description: "Cellery Hub API"
  contact:
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
host: "api.hub.cellery.io"
basePath: "/api/0.1.0"
schemes:
- "https"

paths:
  /auth/token:
    get:
      operationId: "getTokens"
      summary: "Get tokens"
      produces:
      - "application/json"
      parameters:
      - $ref: "#/parameters/authCodeQueryParam"
      - $ref: "#/parameters/callbackUrlQueryParam"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/OrgResponse"
        405:
          description: "Invalid Input"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /orgs:
    post:
      operationId: "createOrg"
      summary: "Create organization"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - $ref: "#/parameters/orgCreateBody"
      responses:
        200:
          description: "OK"
        405:
          description: "Invalid Input"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /orgs/{orgName}:
    get:
      operationId: "getOrg"
      summary: "Get a specific organization"
      produces:
      - "application/json"
      parameters:
      - $ref: "#/parameters/orgNamePathParam"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/OrgResponse"
        405:
          description: "Invalid Input"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"

parameters:
  authCodeQueryParam:
    name: "authCode"
    in: "query"
    description: "Auth code retrieved from a OIDC provider"
    required: true
    type: "string"
  callbackUrlQueryParam:
    name: "callbackUrl"
    in: "query"
    description: "callback Url used in the OIDC flow"
    required: true
    type: "string"
  orgCreateBody:
    name: "organization"
    in: "body"
    description: "Organization which needs to be created"
    required: true
    schema:
      $ref: "#/definitions/OrgCreateRequest"
  orgNamePathParam:
    name: "orgName"
    in: "path"
    description: "Name of the organization"
    required: true
    type: "string"
  orgNameQueryParam:
    name: "orgName"
    in: "query"
    description: "Name of the organization"
    required: false
    type: "string"
  imageNameQueryParam:
    name: "imageName"
    in: "query"
    description: "Name of the Image"
    required: false
    type: "string"
  imageOrderByQueryParam:
    name: "orderBy"
    in: "query"
    description: "The attribute to order the images"
    required: false
    type: "string"
  limitQueryParam:
    name: "limit"
    in: "query"
    description: "Number of results returned for pagination"
    required: true
    type: "number"
  offsetQueryParam:
    name: "offset"
    in: "query"
    description: "Offset of the result set returned for pagination"
    required: true
    type: "number"

definitions:
  TokensResponse:
    type: "object"
    properties:
      accessToken:
        type: "string"
      idToken:
        type: "string"
  OrgCreateRequest:
    type: "object"
    properties:
      orgName:
        type: "string"
      description:
        type: "string"
      websiteUrl:
        type: "string"
      defaultVisibility:
        type: "string"
  OrgResponse:
    type: "object"
    properties:
      description:
        type: "string"
      websiteUrl:
        type: "string"
      author:
        type: "string"
      createdTimestamp:
        type: "string"
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "number"
        description: "API specific error code"
      message:
        type: "string"
        description: "The summarized error message"
      description:
        type: "string"
        description: "Description about the error occurred"

