[security]
certfile="/security/api-tls.crt"
keyfile="/security/api-tls.pem"
trustedcertsfile="/security/trusted-tls.crt"

[portal]
publicurl="https://hub.cellery.io:9000"

[database]
host="mysql.hub.internal"
port=3306
default="CELLERY_HUB"
user="celleryhub"
password="celleryhub"

[filter.captcha]
secret="someSecret"
endpoint="https://www.google.com/recaptcha/api/siteverify"
engaged.paths="[{\"path\" : \"/api/0.1.0/orgs/*\", \"method\": \"get\"}]"

[b7a.log]
level="DEBUG"
